"use client";

import { useAppDispatch, useAppSelector } from '@/store';
import { addOne, initCounterState, substracOne } from '@/store/counter/counterSlice';
import { useEffect, useState } from 'react';
import { IoAddOutline, IoRemoveOutline } from 'react-icons/io5';

interface Props {
    value?: number
}

// Generated by https://quicktype.io

export interface CounterReponse {
    count: number;
}

const getApiCounter = async (): Promise<CounterReponse> => {
    const data = await fetch('/api/counter')
    .then(res => res.json());

    return data;
}

export const CounterHook = ({ value = 10 } : Props) => {
    const count = useAppSelector( state => state.counter.count )
    const dispatch = useAppDispatch()

    useEffect(() => {
        getApiCounter()
        .then( ({ count }) => dispatch( initCounterState(count) ))
    }, [ dispatch ])
    
    return (
        <>
            <span className="text-9xl my-3">{ count }</span>
            <div className="flex">
                <button className="w-20 py-3 rounded-full content-center bg-gray-900 mr-2 hover:bg-gray-700 transition-all" onClick={ () => dispatch( addOne() ) }>
                    <IoAddOutline className="mx-auto" size={ 30 } color="white"/>
                </button>
                <button className="w-20 py-3 rounded-full bg-gray-900 ml-2 hover:bg-gray-700 transition-all" onClick={ () => dispatch( substracOne() ) }>
                    <IoRemoveOutline className="mx-auto" size={ 30 } color="white"/>
                </button>
            </div>
        </>
    )
}
